name: CI/CD Docker Staging (Backend)

on:
  push:
    branches:
      - feature/uorqEraD
    paths:
      - "backend/**"
      - ".github/workflows/deploy_back-test.yaml"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: back_staging

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Check Docker username length
        run: |
            if [ -z "${{ secrets.DOCKER_USERNAME }}" ]; then
                echo "DOCKER_USERNAME is empty!"
                exit 1
            else
                echo "DOCKER_USERNAME is set."
            fi
        
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push image
        uses: docker/build-push-action@v4
        with:
          context: ./backend/Irbags_Api
          file: ./backend/Irbags_Api/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/irbags_api:staging

      - name: Deploy to server via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.STAGING_HOST }}
          username: ${{ secrets.STAGING_USER }}
          key: ${{ secrets.STAGING_SSH_KEY }}
          port: ${{ secrets.STAGING_PORT }}
          script: |
            set -e
            cd C:\Users\downh\source\repos\irbags\backend\Irbags_Api   
            docker pull ${{ secrets.DOCKER_USERNAME }}/irbags_api:staging
            docker compose down || true
            docker compose up -d --no-build
            docker ps --filter "name=api"

