name: CI/CD Docker Staging (Backend)

on:
  push:
    branches:
      - develop
    paths:
      - "Irbags_Api/**"
      - "docker-compose.yml"
      - ".github/workflows/deploy.yml"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Клонируем репозиторий
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Настройка Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # 4. Сборка Docker образа
      - name: Build Docker image
        run: |
          docker build -t irbags-api:staging ./Irbags_Api

      # 5. Обновление контейнера
      - name: Deploy containers
        run: |
          docker-compose -f docker-compose.yml down
          docker-compose -f docker-compose.yml up -d --build
          docker ps
