name: CI/CD Docker Staging (Backend)

on:
  push:
    branches: [ feature/uorqEraD ]
    paths:
      - "backend/**"
      - ".github/workflows/deploy_back-test.yaml"

jobs:
  build-and-deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout кода
        uses: actions/checkout@v4

      - name: Логин в Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Сборка и пуш образа
        uses: docker/build-push-action@v5
        with:
          context: ./backend/Irbags_Api
          file: Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/irbags_api:staging

      - name: Деплой на staging-сервер
        run: |
          cd ./backend/Irbags_Api
          docker pull ${{ secrets.DOCKER_USERNAME }}/irbags_api:staging
          docker compose down || true
          docker compose up -d --no-deps api
          docker ps --filter "name=api"